var options = [
	'Comment about vocal projection',
	'Comment about diction',
	'"I was scared for you!"',
	'Comment about the quality of the script',
	'Comment about the cutting of the script',
	'"What message are you trying to convey with this piece?"',
	'Comment about setup / set change music',
	'Comment about technical crew costumes',
	'"If you drop something, you need to pick it up"',
	'Comment about tending to your props',
	'"Who designed your costumes / set / props / sound / light?"',
	'"Wow! That was quite a show!"',
	'Comment about how appropriate the selection is for the group',
	'"You have such great energy!"',
	'Comment about blocking / sharing the scene',
	'"You looked like you were having so much fun!"',
	'Comment about fight staging and choreography',
	'Comment about setup / set change choreography',
	'Question about research',
	'Comment about lighting choices',
	'Comment about consistency in design work',
	'"Cool concept!"',
	'"Clear, well-executed vision"',
	'"If you are going to do something simple, it needs to be immaculate."',
	'Comment about specificity of choices',
	'Comment about attention to detail ("Straighten your tablecloths!")',
	'"If you put something on stage (set / prop / etc.) you need to use it."',
	'Comment about ensemble work',
	'Comment about period costumes',
	'Comment about the stakes: "Raise the stakes"',
	'Make the judge cry',
	'Comment about transitions',
	'Comment about spatial awareness',
	'Make the judge change their opinion about a piece ("I hate this, but you made me love it!")',
	'Director defends choices',
	'"The audience loved that!"',
	'"This is really picky but…"',
	'"Thank you for sharing your work!"',
	'Comment about giving focus',
	'Pronunciation note',
	'Super esoteric comment (e.g. "I love a good French cleat!")',
	'Comment about the challenge level of the piece',
	'Comment about execution',
	'"I am not here to redirect your piece, but…"',
	'Black on black on black',
	'"This was a really sweet show!"',
	'"I wonder if there is a way to…"',
	'Comment about honesty',
	'Comment about discovery',
	'Comment about beats',
	'"… pulled me out of the world of the play."',
	'"Cheat out"',
	'Comment about sight lines',
	'Random comment that has nothing to do with the show',
	'Shout out to specific actors / characters',
	'"Simplify your set changes."',
	'Adjudicators agree / disagree with one another',
	'Adjudicator asks a question of a specific actor / technician',
	'Comment about intention',
	'Comment about listening',
	'Comment about relationships / establishing relationships',
	'Comment about given circumstances',
	'Comments about hair and makeup',
]

